### ISSUE TITLE
Won't work with my android

### ISSUE THREAD

**Issue by Kiendeleo** [sebsto/AWSVPN#3]
I seem to have this running, however I am unable to connect to it with my android device. Where can I find the logs to try and debug this??

**Comment by sebsto** [comment]
I am sorry to hear you can not connect from your Android device.
As there are many thing that can go wrong in this scenario, I would first try to connect from your local desktop.
If this succeed, it will means the configuration problem is on the mobile device side and that the VPN server is running correctly.

If you find out that the VPN server is not running correctly, these are the log files most likely to contain important information about why a particular tunnel is not succeeding.

```
   /var/log/auth.log
   /var/log/syslog
   /var/log/pluto/peer/a/b/c/d/a.b.c.d.log
```
- The /var/log/auth.log is where logs on the authentication transactions are, stored.
- The /var/log/syslog is the system log, it's always good to check here for any startup or general errors.
- /var/log/pluto/peer/a/b/c/d/a.b.c.d.log file is the per peer pluto log. You can find some of the startup and shutdown information in here.

Let us know how it evolves.

**Comment by sebsto** [comment]
closed because  lack of followup
